### ISSUE TITLE
Render < - > Main Process Communication

### ISSUE THREAD

**Issue by ChrisKader** [michalzaq12/electron-nuxt#129]
A fairly common standard with Electron applications is to use IPC Renderer/IPC Main to communicate between the two processes. The main purpose of this this being security. You normally want to do any kind of file system access and the like from the main process using predefined functions and communicate over IPC.

In my case, I have files on a network share that I need to access and parse through. I also like using the main process for such tasks as I dont lock up the renderer and I can display loading screens and such without choppiness. 

I am trying to figure out the best place to put my handlers. Within BrowserWinHandler.js or in mainWindow.js?

**Comment by michalzaq12** [comment]
Hi @ChrisKader ,
Definitely in mainWindow.js.
BrowserWinHandler is a helper class which should not be edited, it will be moved to separate package in next template version.

**Comment by ChrisKader** [comment]
Thank you @michalzaq12 !

Slightly unrelated, but, when creating an app.html file in my src folder, it seems its not being used as the default one keeps getting put into the .nuxt folder, even if I completely delete the folder and have it regenerate it.

**Comment by ChrisKader** [comment]
Sorry, I was mistaken. Placing it in "renderer" works. But when I make updates to it, the .nuxt files are not regenerated which forces me to delete the folder. Odd.

**Comment by michalzaq12** [comment]
You don't have to create an html template in the NUXT framework, it is generated automatically.

**Comment by namila007** [comment]
> You don't have to create an html template in the NUXT framework, it is generated automatically.

i have added vue files on the PAGES, but when generating (building env) there is only index.html in dist/renderer . no other files i added on pages 
![image](https://user-images.githubusercontent.com/18147085/76909551-7fcfcd80-68d1-11ea-9f57-60c126a1c1c8.png)
![image](https://user-images.githubusercontent.com/18147085/76909576-8eb68000-68d1-11ea-9d4a-24c9001006e9.png)
because of that i cant load windows from file in the production. how to solve this
