### ISSUE TITLE
cross platform compling

### ISSUE THREAD

**Issue by zkcrescent** [michalzaq12/electron-nuxt#168]
how can I build windows version at macos with electron-nuxt? I'm a new electron user, thanks for your help.

**Comment by zkcrescent** [comment]
problem resolved ! I found `electron-builder.Plantform.WINDOWS.createTarget` can create windows targets for cliOptions.targets

**Comment by nwittwer** [comment]
Would love to know this as well. Trying to build for Windows and Mac while using a Mac. I tried the above, but wasn't able to get it working.

Ideally I'd be able to use the [CLI commands](https://www.electron.build/cli) from `electron-builder`, such as adding in `-mw` in an NPM script to build Mac and Windows. Or change my `builder.config.js` file to define which OS builds are created based on which OS I'm using.

**Comment by nwittwer** [comment]
@michalzaq12 Any update on this one? Unclear how to achieve this with the programmatic API for electron-builder. Would be really helpful to have in the documentation.

**Comment by nwittwer** [comment]
Found this https://www.electron.build/#programmatic-usage, but still a few issues:

- Have to modify the `.electron-nuxt/index.js` file because the `publish` and `targets` properties are not exposed to the `builder.config.js` file. Seems like it would be better to modify `builder.config.js`.
- Not clear how to add multiple targets (Windows, Mac) to build for both platforms on Mac. Not currently possible to pass the typical arguments like `--mac --windows` through the build script.
- `@xpda-dev/electron-builder` does not expose the `Platform` property, so it must be imported separately from `electron-builder` package. This is needed for `Platform.OS.createTarget()`.

Could you advise how you would suggest to tackle this? Is it out of scope for your package?

Example to build just for Windows on Mac (`.electron-nuxt/index.js`):
```js
const Platform = require('electron-builder').Platform
const builder = new ElectronBuilder({
  cliOptions: {
    config: path.join(__dirname, '../builder.config.js'),
    targets: Platform.WINDOWS.createTarget()
  }
})
```

Example to use Publish (`.electron-nuxt/index.js`):
```js
require('dotenv').config() // Load GH_TOKEN from .env file
const builder = new ElectronBuilder({
  cliOptions: {
    config: path.join(__dirname, '../builder.config.js'),
    publish: 'always',
  }
})
```

**Comment by michalzaq12** [comment]
Hey @nwittwer, it is a little out of scope from this template.
Due to limitations explained here: https://www.electron.build/multi-platform-build, I advise to compile application only on target platform (using for example Travis service). 
But I will try to add support to target switcher in the next template version.
When it comes to publish option, it should be still possbile using `builder.config.js` (https://www.electron.build/configuration/publish).

`builder.config.js` is the same as `electron-builder.yaml` desribed in electron-builder documentation

**Comment by nwittwer** [comment]
@michalzaq12 Ok! And thanks for links.

Yes, it appears that having this in the `builder.config.js` for each platform you want will trigger the Publish option (as you mentioned: https://www.electron.build/configuration/publish)
```js
mac: {
   publish: ['github']
},
win: {},
linux: {}
```

To follow up (and in case it might help others), I started going down the TravisCI route, and I put together some of the configuration needed to get this project working on it: https://gist.github.com/nwittwer/60aef18c9b4e9506534bdcc0e4a7c3f5. Let me know if you think it would make sense to add any of it to maybe the "Guides > Building notes" section of your documentation.

**Comment by michalzaq12** [comment]
@zkcrescent @nwittwer I added support for the CLI commands from `electron-builder`
https://michalzaq12.github.io/electron-nuxt/guide/#electron-builder-arguments-1-6-0
and created a dedicated [github action](https://github.com/michalzaq12/action-electron-nuxt) for building and releasing cross-platform electron-nuxt apps.


🚀

**Comment by nwittwer** [comment]
@michalzaq12 Looks very detailed and relevant, thanks! I'll let you know once I have a chance to use it
