### ISSUE TITLE
How to get the data of webContents.send () on the non-index page?

### ISSUE THREAD

**Issue by ideacco** [michalzaq12/electron-nuxt#375]
Hello, when I need to initialize, use the browserWindow.webContents.send () function in the rendering process to send data to a nuxt page (non-index page). How can I get it on the page?
(Currently, I can only get data on the index.vue page)
Any help is much appreciated.

**Comment by michalzaq12** [comment]
You can only get data on the index page, because index page is mounted on app startup (so only listeners in index page are active). If you want to listen event from non-index page, this page must be active (mounted). 

There are other ways, it depends on the application architecture. 
- divide app to components, instead of pages
- main file contains all listeners, it is imported in index page
- [...]
